### ISSUE TITLE
Write an 'advance multiple blocks' function for the test helpers

### ISSUE THREAD

**Issue by AndyWatt83** [edgefund/edgefund-core#18]
Already a couple of instances of unit tests looping over the advanceBlock function. A helper method which wraps this up would be useful. 

The easiest way to do this is just to write a helper function which takes an int and loops over the existing function. But, it would be more satisfying to do this with a 'Promise.awaitAll' type call, to take advantage of the async stuff. Maybe overkill. Either method is fine.

**Comment by GarethOates** [comment]
I had wondered about that as well, using Promise.All but I figured it wouldn't actually help anything since the advancement has to be done in series anyway, so there's not really anything to be gained by firing them all off in parallel.

I'd prefer if we can make the tests independent of each other anyway.  At the moment I think the last test in TestCoinToss.js is dependent on the previous test running which advances the block height by x blocks.

I'd rather each test can be run in isolation and still function correctly, so yes, I think using a helper function to do this would be a good idea.
